### PR TITLE
Feature/repo refactoring

### PR DESCRIPTION
**Pull request by sarusso**
@molinaro-m please have a light look and merge the PR. We will use it as demo :)

### CODE REVIEW

**Comment by molinaro-m** [comment]
Wonder if the README can be checked, I experience a formatting issue in the heading syntax

**Review by molinaro-m — CHANGES_REQUESTED** [review]
Please have a look at the README (even if it might be me not checking properly)

**Comment by gtaffoni** [comment]
non ho capito...

**Comment by sarusso** [comment]
Just cleaning the repo we used for some tests in past :)

**Pull request merged**
